# Generated by Django 5.1.6 on 2025-02-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
